#!/bin/bash
# Streamlit Cloud Deployment Helper
# This script provides step-by-step guidance for deploying to Streamlit Cloud

set -e

echo "🚀 Ramadan Bot - Streamlit Cloud Deployment Helper"
echo "=================================================="
echo ""
echo "Since Streamlit Cloud is a web-based service, you'll need to:"
echo ""
echo "STEP 1: Visit https://share.streamlit.io"
echo "        (Make sure you're logged in with GitHub)"
echo ""
echo "STEP 2: Click 'Create app' and fill in:"
echo "        • GitHub repo: fuaadabdullah/ForgeMonorepo"
echo "        • Branch: feat/gradem8-hf-space-2"
echo "        • Main file path: apps/ramadan-bot/streamlit_app.py"
echo ""
echo "STEP 3: Click 'Deploy' and wait 2-3 minutes"
echo ""
echo "STEP 4: Once deployed, add secrets:"
echo "        • Click ☰ menu → Settings"
echo "        • Go to 'Secrets' tab"
echo "        • Paste the template below and fill in your values:"
echo ""
echo "---BEGIN SECRETS TEMPLATE---"
cat apps/ramadan-bot/.streamlit/secrets.toml.example
echo "---END SECRETS TEMPLATE---"
echo ""
echo "✅ Required environment variables:"
echo "   • SENDGRID_API_KEY - Get from SendGrid dashboard"
echo "   • SILICONFLOW_API_KEY - Get from SiliconFlow dashboard"
echo "   • LAT, LON - Your location (use latlong.net)"
echo "   • TZ - Your timezone (e.g., America/New_York)"
echo ""
echo "💡 Pro tips:"
echo "   • After adding secrets, Streamlit will auto-redeploy"
echo "   • Check app logs if deployment fails"
echo "   • Image generation takes 30-60s on free tier"
echo ""
echo "🧪 Test the deployment:"
echo "   1. Open your app URL"
echo "   2. Go to Preview tab → Select Juz → Generate"
echo "   3. Check your email for the Fajr reminder"
echo ""
